### ISSUE TITLE
Improve docs of support for external crate traits

### ISSUE THREAD

**Issue by garro95** [taiki-e/auto_enums#116]
Probably I am missing something.
My compilation fails with the following error:
```
error: cannot find derive macro `ParallelIterator` in this scope
  --> src/main.rs:75:17
   |
75 |     #[auto_enum(ParallelIterator)]
   |                 ^^^^^^^^^^^^^^^^

error: aborting due to previous error
```
In my cargo.toml I have 
```
...
auto_enums = {version = "0.7", features = ["rayon"]}
```
And in my main.rs
```
#![feature(proc_macro_hygiene, stmt_expr_attributes)]
...
use auto_enums::auto_enum;
use rayon::iter::ParallelIterator;
...

fn auto_main() -> Result<(), Error> {
...
    #[auto_enum(ParallelIterator)]
    let iterator =
	if let Some(minsize) = opt.minsize {
	    iterator.filter_map(|r| r.ok().map(|r| r.abitanti > minsize))
	} else {
	    iterator.filter_map(|r| r.ok())
	};

    Ok(())
}
```
Why does it happen?

**Comment by taiki-e** [comment]
To use support for external crate traits, you need to use the path starting with the feature name. 
```diff
-     #[auto_enum(ParallelIterator)]
+     #[auto_enum(rayon::ParallelIterator)]
```

https://github.com/taiki-e/auto_enums/blob/master/docs/supported_traits/external/rayon/ParallelIterator.md

Not being able to write this with just the trait name is a constraint needed to support multiple versions, such as tokio and futures.

**Comment by garro95** [comment]
Oh I see. Thanks. I think this could be made more clear in the documentation.

**Comment by taiki-e** [comment]
Indeed. We can improve docs.
