### ISSUE TITLE
404s in README.md

### ISSUE THREAD

**Issue by Y0ba** [taiki-e/auto_enums#59]
Some links to generated code in readme give 404 error. I.e. 
```markdown
* [`Iterator`](https://doc.rust-lang.org/std/iter/trait.Iterator.html) - [generated code](docs/supported_traits/std/iter/Iterator.md)
```
Either `generated code` should links to [docs/supported_traits/std/iter/**i**terator.md](docs/supported_traits/std/iter/iterator.md) (note lowercase i) or iterator.md should be renamed to Iterator.md.

**Comment by taiki-e** [comment]
@Y0ba Thanks for noticing it. fixed in c8e6d680149fc71ad24bb1dde38f2df575e6b9b6
