### ISSUE TITLE
Similar projects

### ISSUE THREAD

**Issue by xoac** [taiki-e/auto_enums#84]
Maybe adding information to similar projects in README would be good idea?
I found projects like this:
* https://github.com/hobofan/ambassador
* https://gitlab.com/antonok/enum_dispatch

--- 
_And I was looking for crate that would derive [enum sum types](https://github.com/rust-lang/rfcs/issues/2414) in my case I wanted  `tokio::AsyncRead` and `tokio::AsyncWrite` in version 0.1. But it looks like things are in progress what is great information!_

**Comment by taiki-e** [comment]
@xoac Sorry for the late reply!

> Maybe adding information to similar projects in README would be good idea?

Given that I don't have the bandwidth to review/track those projects properly and the readme is already flooded with a lot of information, I think it's preferred not to do that at this time.

> And I was looking for crate that would derive [enum sum types](https://github.com/rust-lang/rfcs/issues/2414) in my case I wanted `tokio::AsyncRead` and `tokio::AsyncWrite` in version 0.1. 

I added Tokio (v0.1 and v0.2) support in 0.7.3 (#92)
