### ISSUE TITLE
Allow #[auto_enum] to be directly used on if expressions

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/auto_enums#86]
Once https://github.com/rust-lang/rust/issues/68618 is resolved, we can support this.

**Comment by Aaron1011** [comment]
This is no longer blocked.

**Comment by Boscop** [comment]
I've been using auto_enums on `let x = if ..` exprs and it's working. Or do you mean `if` exprs without `let`?

Btw, any idea why rustc complains about "unnecessary braces around function argument" after I updated my nightly? https://github.com/rust-lang/rust/issues/71080

**Comment by taiki-e** [comment]
@Boscop 

> Or do you mean `if` exprs without `let`?

Yes, basically I want to annotate `if` expressions without depending on `let`.

Practically the same as the current one, it would be nice to support the following styles:

```rust
#[auto_enum]
fn a() {
    let res = {
        // This is the same as using #[auto_enum] on `let`, 
        // but maybe easier to read depending on the length of the block.
        #[auto_enum]
        if x {
            // ...
        } else {
            // ...
        }
    };
}

#[auto_enum]
fn a() -> Option<impl Foo> {
    // Equivalent to `#[auto_enum] let res = if ...` and `Some(res)`
    Some(#[auto_enum] if x { y } else { x })
}
```

And, these are already available on `match` expressions, so we can provide more consistent support.

**Comment by taiki-e** [comment]
> Btw, any idea why rustc complains about "unnecessary braces around function argument" after I updated my nightly? [rust-lang/rust#71080](https://github.com/rust-lang/rust/issues/71080)

Thanks for reporting it, I will look into it.

**Comment by taiki-e** [comment]
> And, these are already available on `match` expressions, so we can provide more consistent support.

Oh..., this comment is not correct. The second example does not work without unstable features even if I replace `if` with a `match` (#90, if I have unstable features enabled, both will work.)
Also, the first example actually seems to be already supported. (#89)
